name: lzliangzh
on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:  # mkdocs-blogging-plugin 给出的渲染问题解决方案
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs
      - run: pip install mkdocs-material
      - run: pip install mkdocs-blogging-plugin  # 记得安装其他依赖的库
      - run: pip install mkdocs-callouts
      - run: pip install mkdocs-meta-manager
      - run: pip install mkdocs-meta-descriptions-plugin
      - run: pip install mkdocs-mermaid2-plugin
      - run: pip install mkdocs-add-number-plugin
      - run: pip install mkdocs-footermatter mkdocs-encryptcontent-plugin
      
      - run: mkdocs gh-deploy --force
